// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).factory('userService', function($rootScope) {
    var isActive;
    isActive = {};
    return {
      isActive: isActive
    };
  });

}).call(this);

/*
//@ sourceMappingURL=AuthenticationService.map
*/
