// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('createUserCtrl', function($scope, $location, $rootScope, $http, $timeout, userService) {
    if (localStorage.username === void 0) {
      $location.path('#/login');
    }
    $scope.userList = userService.user_employer;
    return $scope.createUser = function() {
      var user;
      if ($scope.data.username !== void 0 && $scope.data.password !== void 0 && $scope.data.confirmPassword !== void 0) {
        user = {
          id: _.max(userService.user_employer, function(user) {
            return user.id;
          }).id + 1,
          username: $scope.data.username,
          password: $scope.data.password,
          role: 'employer'
        };
        userService.user_employer.push(user);
        $scope.errorMode = true;
        $timeout((function() {
          return $timeout((function() {
            return $scope.errorMode = false;
          }), 300);
        }), 300);
        return $scope.data = null;
      } else {
        return console.log('Please fill the details');
      }
    };
  }).directive("passwordVerify", function() {
    return {
      require: "ngModel",
      scope: {
        passwordVerify: "="
      },
      link: function(scope, element, attrs, ctrl) {
        scope.$watch((function() {
          var combined;
          combined = void 0;
          if (scope.passwordVerify || ctrl.$viewValue) {
            combined = scope.passwordVerify + "_" + ctrl.$viewValue;
          }
          return combined;
        }), function(value) {
          if (value) {
            ctrl.$parsers.unshift(function(viewValue) {
              var origin;
              origin = scope.passwordVerify;
              if (origin !== viewValue) {
                ctrl.$setValidity("passwordVerify", false);
                return undefined;
              } else {
                ctrl.$setValidity("passwordVerify", true);
                return viewValue;
              }
            });
          }
        });
      }
    };
  });

}).call(this);
