// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('createResistantCoefficientsCtrl', function($scope, ReitzResources, $cookieStore) {
    var coefficients;
    if ($cookieStore.get('id') === void 0) {
      $location.path('#/login');
    }
    $scope.FanAssemblies = [
      {
        label: 'Inlet Sound Silencer',
        value: 0,
        pId: 10
      }, {
        label: 'Inlet Box',
        value: 1,
        pId: 11
      }, {
        label: 'Other Inlet parts',
        value: 2,
        pId: 12
      }, {
        label: 'Outlet Silencer',
        value: 3,
        pId: 13
      }, {
        label: 'Other Outlet Parts',
        value: 4,
        pId: 14
      }
    ];
    $scope.getFanAssembliesName = $scope.FanAssemblies[0];
    coefficients = ReitzResources.multiunitsdata.query();
    return $scope.addCofficients = function(val, ob) {
      var data;
      data = {
        'Name': ob.label,
        'DisplayText': val,
        'Value': val,
        'ParentId': ob.pId,
        'Type': 1,
        'ParentDetails': null
      };
      if (_.find(coefficients, {
        ParentId: ob.pId,
        Value: val,
        Type: 1
      })) {
        $scope.errorModeExists = true;
        $timeout((function() {
          return $timeout((function() {
            return $scope.errorModeExists = false;
          }), 300);
        }), 300);
        return $scope.data = null;
      } else {
        return ReitzResources.multiunitsdata.create(data).$promise.then(function(values) {
          coefficients.push(values);
          $scope.errorMode = true;
          $timeout((function() {
            return $timeout((function() {
              return $scope.errorMode = false;
            }), 300);
          }), 300);
          return $scope.data = null;
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=createResistantCoefficientsCtrl.map
*/
