// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('createImpellerScantllingsCtrl', function($scope, $location, $cookieStore, chartService, $http, ReitzResources) {
    var scantillings;
    if ($cookieStore.get('id') === void 0) {
      $location.path('#/login');
    }
    scantillings = ReitzResources.ImpellerScantllingValues.query();
    return $scope.addImpleller = function(data) {
      var obj;
      obj = {
        Backplate_mm: +data,
        Blade_mm: +data,
        Shroud_mm: +data
      };
      if (_.find(scantillings, obj)) {
        $scope.errorModeExists = true;
        $timeout((function() {
          return $timeout((function() {
            return $scope.errorModeExists = false;
          }), 300);
        }), 300);
        return $scope.data = null;
      } else {
        return $http.post('http://202.153.45.8/ReitzService/api/ImpellerScantllingValues', obj).success(function(val) {
          scantillings.push(val);
          $scope.errorMode = true;
          $timeout((function() {
            return $timeout((function() {
              return $scope.errorMode = false;
            }), 300);
          }), 300);
          return $scope.data = null;
        });
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=createImpellerScantllingsCtrl.map
*/
