// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var app;
    app = void 0;
    app = angular.module("reitz");
    app.controller("CustomerProjectsListController", function($scope, $location, $cookieStore, ReitzResources, projectservice, $filter, ngTableParams) {
      var projectsList;
      if ($cookieStore.get('id') === void 0) {
        $location.path('#/login');
      }
      projectsList = function() {
        return $scope.tableList = new ngTableParams({
          page: 1,
          count: 5
        }, {
          counts: [],
          total: 0,
          getData: (function($defer, params) {
            var filteredData, orderedData;
            filteredData = params.filter() ? $filter('filter')($scope.projectslist, params.filter()) : $scope.projectslist;
            orderedData = params.sorting() ? $filter('orderBy')(filteredData, params.orderBy()) : $scope.projectslist;
            params.total(orderedData.length);
            return $defer.resolve(orderedData.slice((params.page() - 1) * params.count(), params.page() * params.count()));
          }),
          $scope: $scope
        });
      };
      ReitzResources.fanproject.query().$promise.then(function(result) {
        if (!_.isEmpty(result)) {
          $scope.projectslist = result;
          return projectsList();
        }
      });
      return $scope.sendData = function(obj) {
        obj.FanAssemblies.InletBox = obj.FanAssemblies.InletBox.toString();
        obj.FanAssemblies.InletOtherParts = obj.FanAssemblies.InletOtherParts.toString();
        obj.FanAssemblies.InletSoundSilencer = obj.FanAssemblies.InletSoundSilencer.toString();
        obj.FanAssemblies.OutletOtherParts = obj.FanAssemblies.OutletOtherParts.toString();
        obj.FanAssemblies.OutletSilencer = obj.FanAssemblies.OutletSilencer.toString();
        obj.FanAssemblies.Pressure_Difference = obj.FanAssemblies.Pressure_Difference.toString();
        obj.MaterialDriveControls.Width = obj.MaterialDriveControls.Width.toString();
        obj.GasOperatingPoint = obj.GasOperatingPoints[obj.GasOperatingPoints.length - 1];
        projectservice.FanCoeffients = ReitzResources.multiunitsdata.query();
        projectservice.data = obj;
        projectservice.data.countVariables = {
          VpCount: 0,
          DptCount: 0
        };
        return $location.url("/edit/project");
      };
    });
  }).call(this);

}).call(this);

/*
//@ sourceMappingURL=CustomerProjectsListController.map
*/
