// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('CustomerLoginController', function($scope, $rootScope, $location, $http, userService) {
    $scope.logout = function() {
      return localStorage.removeItem('username');
    };
    if ($location.path() === '/login') {
      $scope.logout();
    }
    return $scope.customerViews = function(login) {
      if (login.username === userService.user_admin.username && login.password === userService.user_admin.password && userService.user_admin.role === 'admin') {
        $scope.errorMode = false;
        userService.isActive = userService.user_admin;
        localStorage.username = login.username;
        return $location.path('/home');
      } else {
        return _.filter(userService.user_employer, function(user) {
          if (user.username === login.username && user.password === login.password && user.role === 'employer') {
            $scope.errorMode = false;
            userService.isActive = user;
            localStorage.username = login.username;
            return $location.path('/home');
          } else {
            $scope.errorMode = true;
            return $scope.userlogin = '';
          }
        });
      }
    };
  });

}).call(this);
