// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('materialControlController', function($scope, $route, $cookieStore, $location, $routeParams, $rootScope, projectservice, ReitzResources, chartService) {
    $scope.state = $routeParams['state'];
    if ($cookieStore.get('id') === void 0) {
      $location.path('#/login');
    }
    $scope.data = projectservice.data;
    $scope.$watch('data.MaterialDriveControls.MechanicalDesignTemperature > 350', (function(value) {
      if (value) {
        return $scope.data.MaterialDriveControls.StandardImpellerMaterial = false;
      } else {
        return $scope.data.MaterialDriveControls.StandardImpellerMaterial = true;
      }
    }), true);
    $scope.$watch('data.MaterialDriveControls.Drive ', (function(value) {
      if (value === "K") {
        $scope.data.MaterialDriveControls.direct = true;
        return $scope.data.MaterialDriveControls.IECStandardMotor = false;
      } else {
        $scope.data.MaterialDriveControls.direct = false;
        return $scope.data.MaterialDriveControls.IECStandardMotor = true;
      }
    }), true);
    $scope.$watch('data.MaterialDriveControls.Control ', (function(value) {
      if (value === "2") {
        return $scope.data.MaterialDriveControls.IVCPosition = true;
      } else {
        return $scope.data.MaterialDriveControls.IVCPosition = false;
      }
    }), true);
    return $scope.resultview = function() {
      chartService.postdata = $scope.data;
      $rootScope.navEnable = true;
      return $location.path('/' + $scope.state + '/chartview');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=materialControlController.map
*/
