// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('noiseDataController', function($scope, $route, $cookieStore, $location, $routeParams, $rootScope, projectservice, ReitzResources, chartService) {
    $scope.state = $routeParams['state'];
    if ($cookieStore.get('id') === void 0) {
      $location.path('#/login');
    }
    $scope.data = projectservice.data;
    return $scope.createProject = function(data) {
      chartService.postdata = $scope.data;
      $rootScope.navEnable = true;
      return $location.path('/' + $scope.state + '/chartview');
    };
  });

}).call(this);

/*
//@ sourceMappingURL=noiseDataController.map
*/
