// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).controller('ProjectDataController', function($scope, $route, $routeParams, $location, $rootScope, projectservice) {
    $scope.state = $routeParams['state'];
    if (localStorage.username === void 0) {
      $location.path('#/login');
    }
    return $scope.data = projectservice.data;
  });

}).call(this);
