// Generated by CoffeeScript 1.6.3
(function() {
  (angular.module('reitz')).factory('ReitzResources', function($resource, $http) {
    return {
      fanproject: $resource('http://202.153.45.8/ReitzService/api/FanProject/', {}, {
        query: {
          method: 'GET',
          isArray: true
        },
        create: {
          method: 'POST'
        }
      }),
      fanseries: $resource('http://202.153.45.8/ReitzService/api/FanSeries/:id', {}, {
        query: {
          method: 'GET'
        }
      }),
      multiunitsdata: $resource('http://202.153.45.8/ReitzService/api/MultiDisplayControlData/', {}, {
        query: {
          method: 'GET',
          isArray: true
        },
        create: {
          method: 'POST'
        }
      }),
      fanresultpost: $resource('http://sikkimgazettes.technoidentity.com/api/Values', {}, {
        query: {
          method: 'GET',
          isArray: true
        },
        create: {
          method: 'POST',
          isArray: true
        }
      }),
      shaftDiaHub: $resource(' http://202.153.45.8/ReitzService/api/RpmType/:rpm/:range1', {}, {
        query: {
          method: 'GET',
          isArray: true
        }
      }),
      ImpellerScantllingValues: $resource(' http://202.153.45.8/ReitzService/api/ImpellerScantllingValues', {}, {
        query: {
          method: 'GET',
          isArray: true
        }
      }),
      getInletBoxWeitghts: function(cb) {
        return $http.get("http://202.153.45.8/ReitzService/GrossWeightOfInletBoxes").success(function(data) {
          return cb(data);
        }).error(function(error) {
          return console.log(error);
        });
      }
    };
  });

}).call(this);
